//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarritosProductos
    {
        public int idCarritoProducto { get; set; }
        public int idCarrito { get; set; }
        public int idProducto { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public decimal PrecioPorProducto { get; set; }
        public int Cantidad { get; set; }
    }
}
