//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarritosProductos
    {
        public int idCarritoProducto { get; set; }
        public string idCarrito { get; set; }
        public string idProducto { get; set; }
        public decimal Precio { get; set; }
        public System.DateTime FechaIngreso { get; set; }
    }
}
