//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetodosPagoUsuarios
    {
        public int idMetodo { get; set; }
        public int idUsuario { get; set; }
        public string Tipo { get; set; }
        public string Numero { get; set; }
        public Nullable<System.DateTime> FechaExpiracion { get; set; }
        public string CVV { get; set; }
        public bool EsPrincipal { get; set; }
    }
}
