//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int idProducto { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int SumaValoraciones { get; set; }
        public int CantidadValoraciones { get; set; }
        public decimal Precio { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public bool EstaActivo { get; set; }
    }
}
